# Generated by Django 5.1.3 on 2024-11-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
