# Generated by Django 5.1.3 on 2024-11-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_alter_contacts_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
