# Generated by Django 5.1.3 on 2024-11-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_remove_contacts_phone_number_contacts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
